---
title: ''
  html_document:
    df_print: paged
---

\newpage

# `r fontawesome::fa("calendar-alt")` Class schedule. 

`r fontawesome::fa("chart-line")` EMF, Fall 2023. 

Room 1411, 17:30 – 19:00.

Zoom [https://us02web.zoom.us/j/81718764251](https://us02web.zoom.us/j/81718764251)

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1. `r fontawesome::fa("handshake")` Thursday, 3 August.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp and Deepnote accounts. You should have received invitations in your UDEM student email.
- Activity. Define your group of no more than 4 members. You should have received an invitation in your UDEM student email.

**Session 2. Monday, 7 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 1 *Getting started*.
- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 2 *Time series graphics*.
- Extra marks 1/8. DataCamp course: *Introduction to ChatGPT*, before 7:00 a.m.

**Session 3. Thursday, 10 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 2 *Time series graphics*.

**Session 4. Monday, 14 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 3 *Time series decomposition*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.
- Extra marks 2/8. DataCamp skill track: *Time Series with R*, before 7:00 a.m.

**Session 5. Thursday, 17 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 3 *Time series decomposition*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.
- Complementary material. Video: [Rob Hyndman, How Rmarkdown changed my life, RStudio 2020.](https://youtu.be/_D-ux3MqGug)

**Session 6. Monday, 21 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 5 *The forecaster’s toolbox*.
- Complementary material. Video: [Chapter 5.](https://youtu.be/6mXUz_l3mPQ)
- We do not review @49018680cf534023b6ae0f4e933c475d, Chapter 4, but here is one interesting video about this chapter in case you are interested. [Talk time series data.](https://youtu.be/Ykiuj16P450) @49018680cf534023b6ae0f4e933c475d video: [Chapter 4.](https://youtu.be/pSdFzYsR0rQ)

**Session 7. Thursday, 24 August.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 5 *The forecaster’s toolbox*.
- We do not review @49018680cf534023b6ae0f4e933c475d, Chapter 6, but here is one interesting video about this chapter in case you are interested. [Chapter 6.](https://youtu.be/4cjU4NV1tkk)
- Extra marks 3/8. [Sustainable Diet.](https://unccelearn.org/course/view.php?id=56&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.
- Complementary material. [The Plastic Recycling Myth.](https://youtu.be/zZlRhCDzh2A)

**Session 8, Zoom. Monday, 28 August.**

- Extra marks. $ME_1$ Instructions in Blackboard.

**Session 9, Zoom. Thursday, 31 August.**

- Activity. $H_1$ review.
- Extra marks. Mentimeter 1/3.

**Session 10, Zoom. Monday, 4 September.**

- Graded. Complete $H_1$ before 7:00 a.m.
- Activity. Discuss $H_1$ answers.
- Activity. $E_1$ review.
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)

**Session 11, Zoom. Thursday, 7 September.**

- Graded. $E_1$ Instructions in Blackboard.

## `r fontawesome::fa("battery-half")` Part 2.

**Session 12, Zoom. Monday, 11 September.**

- Activity. Discuss $E_1$ answers.
- Extra marks. The wheel of fortune 1/3.
- Graded. Submit $H_1$ and $E_1$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.

**Session 13. Thursday, 14 September.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 7 *Time series regression models*.
- To know more about *Time series regression and forecasting*, please see @hanck2020introduction, Chapter 14.
- Extra marks 4/8. DataCamp skill track: *Supervised Machine Learning in R*, before 7:00 a.m.

**Session 14. Monday, 18 September.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 7 *Time series regression models*.

**Session 15. Thursday, 21 September.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 8 *Exponential smoothing*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.
- Complementary material. @49018680cf534023b6ae0f4e933c475d videos: 8.1 [Simple exponential smoothing.](https://youtu.be/E47o0TrFBIg) 8.2 [Holt's linear trend method.](https://youtu.be/tMaEhMmLgxs) 8.3 [Holt Winters smoothing.](https://youtu.be/Mtu3_eIgSg0) 8.7 [ETS models.](https://youtu.be/QnBGtvKnGqk)

**Session 16. Monday, 25 September.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 8 *Exponential smoothing*.
- Extra marks 5/8. DataCamp skill track: *Unsupervised Machine Learning with R*, before 7:00 a.m.

**Session 17. Thursday, 28 September.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 9 *ARIMA models*.
- Complementary material. @49018680cf534023b6ae0f4e933c475d videos: 9.1 [ARIMA unit root test.](https://youtu.be/xgIu7H2Qo64) 9.3 [ARIMA Autoregressive models.](https://youtu.be/7fN_b1BihWM) 9.4 [ARIMA ARMA model.](https://youtu.be/rWDhcSau1lg) 9.5 [ARIMA, non seasonal.](https://youtu.be/KbzCi2qD9eg) 9.9 [Seasonal ARIMA.](https://youtu.be/3UImzupolm0)

**Session 18, Zoom. Monday, 2 October.**

- Extra marks. $ME_2$ Instructions in Blackboard.
- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 9 *ARIMA models*.
- Complementary material. Video: [Times-series analysis.](https://youtu.be/OzpZVMfaszY)
- To know more about ARIMA models see @ruppert2011statistics: Chapters 12 and 13.

**Session 19, Zoom. Thursday, 5 October.**

- Activity. $H_2$ review.
- Extra marks. Mentimeter 2/3.
- Reading. @lozanoEMF, Chapter 3 *Forecasts with h2o*.
- Reading. @lozanoEMF, Chapter 4 *Two more forecast models*.
- Reading. @lozanoEMF, Chapter 5 *Summary of all results*.

**Session 20, Zoom. Monday, 9 October.**

- Graded. Complete $H_2$ before 7:00 a.m.
- Activity. Discuss $H_2$ answers.
- Activity. $E_2$ review.

**Session 21, Zoom. Thursday, 12 October.**

- Graded. $E_2$ Instructions in Blackboard.

## `r fontawesome::fa("battery-three-quarters")` Part 3 & COIL.

**Session 22, Zoom. Monday, 16 October.**

- Activity. Discuss $E_2$ answers.
- Extra marks. The wheel of fortune 2/3.
- Graded. Submit $H_2$ and $E_2$ auto and co-evaluation before 7:00 a.m. Instructions in Blackboard.

**Session 23. Thursday, 19 October.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 10 *Dynamic regression models*.
- Complementary material. @49018680cf534023b6ae0f4e933c475d video: [Introduction to dynamic regression.](https://youtu.be/F2ByLxVlCtM)

**Session 24. Monday, 23 October.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 10 *Dynamic regression models*.
- Extra marks 6/8. [An Introduction to Climate Change and Human Rights.](https://unccelearn.org/course/view.php?id=136&page=overview) Submit your PDF certificate before 7:00 a.m. by the discussion forum.
- COIL. Video intercultural.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 25. COIL 1/4. Thursday, 26 October, 18:00 – 19:00.**

- COIL. Bienvenida y presentaciones.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 26. Monday, 30 October.**

- Extra marks. Mentimeter 3/3.
- Extra marks 7/8. DataCamp skill track: *Machine Learning Fundamentals with Python*, before 7:00 a.m.
- COIL. Ensayos. Análisis de datos.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 27. COIL 2/4. Thursday, 2 November, 18:00 – 19:00.**

- COIL. Presentaciones. Análisis de datos.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 28, Zoom. Monday, 6 November.**

- Extra marks. $ME_F$ Instructions in Blackboard.
- Extra marks 8/8. DataCamp skill track: *Time Series with Python*, before 7:00 a.m.
- COIL. Ensayos. Metodología y resultados.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 29. COIL 3/4. Zoom. Thursday, 9 November, 18:00 – 19:00.**

- COIL. Presentaciones. Metodología y resultados.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 30, Zoom. Monday, 13 November.**

- Non graded. Complete $H_3$ before 7:00 a.m.
- Activity. $E_F$ review.
- Extra marks. The wheel of fortune 3/3.
- Farewell.

**Session 31. COIL 4/4. Thursday, 16 November, 18:00 – 19:00.**

- COIL. Presentaciones. Conclusiones.
- Nota: Las instrucciones de la actividad COIL están disponibles en Blackboard.

**Session 32, Zoom. Tuesday, 21 November.**

- Review.

## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Thursday, 30 November, 16:00 – 18:00.**

- Graded. $E_F$ Instructions in Blackboard.

\newpage









