# `r fontawesome::fa("calendar-alt")` Schedule. {#sec-schedule}

`r fontawesome::fa("chart-line")` EMF, Spring 2025. Room  1305, Monday & Thursday 17:30 – 19:00. Zoom [https://us02web.zoom.us/j/89010528554](https://us02web.zoom.us/j/89010528554)

## `r fontawesome::fa("battery-quarter")` Part 1.

**Session 1, Zoom. `r fontawesome::fa("handshake")` Monday, January 13.**

- Reading. Course syllabus (this document).
- Activity. Welcome and introduction to the course.
- Activity. Set up your free DataCamp account. Invitations have been sent to your UDEM student email.
- Activity. Define your team of no more than 4 members.
- Extra marks. Quiz 1. At 6:30 p.m., Quiz 1 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity; you will have 25 minutes to complete it, and access to the quiz will close at 6:40 p.m. Quiz 1 consists of 10 true/false questions about the syllabus, with each question worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class.

**Session 2, Zoom. Thursday, January 16.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 1 *Getting started*.
- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 2 *Time series graphics*.
- Extra marks. Quiz 2. At 6:30 p.m., Quiz 2 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity; you will have 25 minutes to complete it, and access to the quiz will close at 6:40 p.m. Quiz 2 consists of 10 true/false questions about the syllabus, with each question worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class. Quiz 1 and Quiz 2 are from the same question pool, so it is possible that you may encounter some repeated questions from Quiz 1.

**Session 3, Zoom. Monday, January 20.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 2 *Time series graphics*.
- Extra marks. Quiz 3. At 6:30 p.m., Quiz 3 will be available on Blackboard in the "Homeworks & exams" section. This is an in-class activity, and you will have 25 minutes to complete it. Access to the quiz will close at 6:40 p.m. Quiz 3 consists of 10 true/false questions about the syllabus, at a higher level of difficulty compared to Quiz 1 and Quiz 2. Each question is worth 0.5 points, allowing you to earn up to +5 extra points on your $E_1$ if answered correctly. With this activity, we will conclude the class. 

**Session 4, Zoom. Thursday, January 23.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 3 *Time series decomposition*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.

**Session 5, Zoom. Monday, January 27.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 3 *Time series decomposition*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.
- Complementary material. Video: [Rob Hyndman, How Rmarkdown changed my life, RStudio 2020.](https://youtu.be/_D-ux3MqGug)

**Session 6, Zoom. Thursday, January 30.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 5 *The forecaster’s toolbox*.
- Complementary material. Video: [Chapter 5.](https://youtu.be/6mXUz_l3mPQ)
- We do not review @49018680cf534023b6ae0f4e933c475d, Chapter 4, but here is one interesting video about this chapter in case you are interested. [Talk time series data.](https://youtu.be/Ykiuj16P450) @49018680cf534023b6ae0f4e933c475d video: [Chapter 4.](https://youtu.be/pSdFzYsR0rQ)
- Activity. $H_1$ review.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, February 3.**

**Session 7. Thursday, February 6.**

- Graded. Complete $H_1$ before 10:00 a.m.
- Activity. $H_1$ presentations.

**Session 8. Monday, February 10.**

- Activity. $E_1$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.
- Extra marks. DataCamp top 5 XP for the first 30 days. Wednesday, February 12.

**Session 9, Zoom. `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")` Thursday, February 13.**

- Graded. $E_1$ Instructions in Blackboard.

## `r fontawesome::fa("battery-half")` Part 2.

**Session 10. Monday, February 17.**

- Activity. Discuss $E_1$ answers.
- Extra marks. The wheel of fortune 1/3. This is a class activity.
- Graded. Submit $H_1$ and $E_1$ co-evaluation before 10:00 a.m. Instructions in Blackboard.

**Session 11. Thursday, February 20.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 7 *Time series regression models*.
- To know more about *Time series regression and forecasting*, please see @hanck2020introduction, Chapter 14.
- We do not review @49018680cf534023b6ae0f4e933c475d, Chapter 6, but here is one interesting video about this chapter in case you are interested. [Chapter 6.](https://youtu.be/4cjU4NV1tkk)
- Complementary material. [The Plastic Recycling Myth.](https://youtu.be/zZlRhCDzh2A)

**Session 12. Monday, February 24.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 7 *Time series regression models*.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 180 por favor.*

**Session 13. Thursday, February 27.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 8 *Exponential smoothing*.
- Reading. @lozanoEMF, Chapter 1 *The forecast problem*.
- Reading. @lozanoEMF, Chapter 2 *Forecasts with fpp3*.
- Complementary material. @49018680cf534023b6ae0f4e933c475d videos: 8.1 [Simple exponential smoothing.](https://youtu.be/E47o0TrFBIg) 8.2 [Holt's linear trend method.](https://youtu.be/tMaEhMmLgxs) 8.3 [Holt Winters smoothing.](https://youtu.be/Mtu3_eIgSg0) 8.7 [ETS models.](https://youtu.be/QnBGtvKnGqk)

**Session 14. Monday, March 3.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 8 *Exponential smoothing*.

**Session 15. `r fontawesome::fa("female")` Thursday, March 6.**

- Activity. $H_2$ review.
- Extra marks. Actividad +5 puntos sobe la calificación del segundo parcial. Compartir, reaccionar y/o agregar un comentario en redes sociales. Subir evidencia (screenshot) al foro de discusión del segundo parcial. La hora límite es 10:00 a.m. de la sesión 15: (1) *Retos y oportunidades en el aprendizaje de ciencia de datos en las escuelas de negocios.* [Spotify `r fontawesome::fa("spotify")`](https://open.spotify.com/episode/6x8c6XIPIfIPLj1yRhi5D8?si=bcee2af66ed54e09); [YouTube `r fontawesome::fa("youtube")`](https://youtu.be/SKG3Kr-TK-w?si=W5wg2DXluuiEspWC); [LinkedIn `r fontawesome::fa("linkedin")`](https://www.linkedin.com/posts/martin-lozano-21818a22_132-retos-y-oportunidades-en-el-aprendizaje-activity-7142212773349945344-1xHL?utm_source=share&utm_medium=member_desktop). Café de Datos, Datlas. Temporada 9, capítulo 132. Diciembre 2023. (2) *Riesgo financiero.* [Spotify `r fontawesome::fa("spotify")`](https://open.spotify.com/episode/7hrOh0tvDH3lioOfXtRqsT?si=8142007bc6ab4f56). Hablemos de economía y política. Asociación para la Conciencia Económica y Política (ACEyP). Noviembre 2024.

**Session 16. Monday, March 10.**

- Graded. Complete $H_2$ before 10:00 a.m.
- Activity. $H_2$ presentations.

**Session 17. $\pi$ Thursday, March 13.**

- Activity. $E_2$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.
- Extra marks. DataCamp top 5 XP for the days 31 to 60. Friday, March 14.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, March 17.**

**Session 18, Zoom. Thursday, March 20.**

- Graded. $E_2$ Instructions in Blackboard.

## `r fontawesome::fa("battery-three-quarters")` Part 3.

**Session 19, Zoom. Monday, March 24.**

- Activity. Discuss $E_2$ answers.
- Extra marks. The wheel of fortune 2/3. This is a class activity.
- Graded. Submit $H_2$ and $E_2$ co-evaluation before 10:00 a.m. Instructions in Blackboard.

**Session 20. Thursday, March 27.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 9 *ARIMA models*.
- Complementary material. Video: [Times-series analysis.](https://youtu.be/OzpZVMfaszY)
- To know more about ARIMA models see @ruppert2011statistics: Chapters 12 and 13.
- Complementary material. @49018680cf534023b6ae0f4e933c475d videos: 9.1 [ARIMA unit root test.](https://youtu.be/xgIu7H2Qo64) 9.3 [ARIMA Autoregressive models.](https://youtu.be/7fN_b1BihWM) 9.4 [ARIMA ARMA model.](https://youtu.be/rWDhcSau1lg) 9.5 [ARIMA, non seasonal.](https://youtu.be/KbzCi2qD9eg) 9.9 [Seasonal ARIMA.](https://youtu.be/3UImzupolm0)

**Session 21. Monday, March 31.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 9 *ARIMA models*.

**Session 22. Thursday, April 3.**

- Presentaciones proyectos PEF2.

**Session 23. Monday, April 7.**

- Reading. @lozanoEMF, Chapter 3 *Forecasts with h2o*.
- Reading. @lozanoEMF, Chapter 4 *Two more forecast models*.
- Reading. @lozanoEMF, Chapter 5 *Summary of all results*.

**Session 24, Zoom. Thursday, April 10.**

- Reading. @49018680cf534023b6ae0f4e933c475d, Chapter 10 *Dynamic regression models*.
- Complementary material. @49018680cf534023b6ae0f4e933c475d video: [Introduction to dynamic regression.](https://youtu.be/F2ByLxVlCtM)
- Non graded. Mention DataCamp in social media if possible. [Instructions.](https://docs.google.com/document/d/1Dv-L036CZWsZCmn9W5p0ikgetlc4GcT-NQ9Rp_HebE0/edit)
- Extra marks. DataCamp top 5 XP for the days 61 to 90. Monday, April 14.

**Holiday. `r fontawesome::fa("umbrella-beach")` Monday, April 14.**

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, April 17.**

**Session 25. Monday, April 21.**

- Reading. @49018680cf534023b6ae0f4e933c475d,
Chapter 12 *Advanced forecasting methods*.

**Session 26. Thursday, April 24.**

- Reading. @49018680cf534023b6ae0f4e933c475d,
Chapter 12 *Advanced forecasting methods*.

**Session 27. `r fontawesome::fa("children")` Monday, April 28.**

- Guest lecturer.

**Holiday. `r fontawesome::fa("umbrella-beach")` Thursday, May 1.**

**Session 28, Zoom. `r fontawesome::fa("jedi-order")` Monday, May 5.**

- Guest lecturer.
- Non-graded. Complete $H_3$ before 10:00 a.m.
- *No conozco la fecha límite, pero deben completar la encuesta avanza 360 por favor.*

**Session 29, Zoom. Thursday, May 8.**

- Activity. $E_F$ review.
- Extra marks. Complete DataCamp assignments. It is not required to send evidence of having completed the tasks because the system automatically records if they were completed on time.
- Extra marks. Complete one UN CC:Learn course. Submit your PDF certificate before 10:00 a.m. by the discussion forum.
- Extra marks. The wheel of fortune 3/3. This is a class activity.
- Farewell `r fontawesome::fa_i("heart", class = "fa-solid", style = "color: red;")`.

## `r fontawesome::fa("battery-full")` The end.

**Final exam, Zoom. Thursday, May 15, 16:00 – 18:00.**

- Graded. $E_F$ Instructions in Blackboard.